# Generated by Django 6.1 on 2026-08-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(help_text='The page this banner belongs to, exactly as the file is named, e.g. "Cookware-Non-Stick.html".', max_length=120, unique=True)),
                ('label', models.CharField(blank=True, help_text='What to call it in this list. Left blank, the page name is used.', max_length=120)),
                ('image', models.ImageField(help_text='A wide, short photograph - around 5:1, at least 1900px across. Shoot or crop it with the product to the RIGHT and empty space to the LEFT, because the heading sits on the left.', upload_to='category-banners/')),
                ('focus', models.PositiveSmallIntegerField(default=74, help_text='Which part of the photo to keep on a computer, as a percentage across it. Only about half the width fits, so this slides the visible window: lower moves the subject right, higher moves it left.')),
                ('mobile_focus', models.PositiveSmallIntegerField(default=82, help_text='The same, for phones. Phones crop tighter, so the subject usually needs to sit further along.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to fall back to the banner the site already ships for this page, without deleting this one.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category banner',
                'verbose_name_plural': 'Category banners',
                'ordering': ['page'],
            },
        ),
    ]
