# Generated by Django 6.1 on 2026-08-24 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_brand_catalogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_hero',
            field=models.BooleanField(default=False, help_text='Use as the main/large photo for this product (or this variant, if set).'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='variant',
            field=models.ForeignKey(blank=True, help_text="Leave blank for a general product photo. Set this to attach the photo to one specific size/variant only — e.g. so the '16 cm' variant shows its own pan instead of the 14 cm one.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productvariant'),
        ),
    ]
