# Generated by Django 6.1 on 2026-08-24 05:27

from django.db import migrations, models


def mark_existing_as_bulk_imported(apps, schema_editor):
    # Every Product row that already exists at this point came from the one-time
    # sync_products.py import of the pre-existing site catalogue, not from someone
    # using the dashboard — so it must NOT be re-exported (that would duplicate the
    # whole catalogue in product-data/products.json). Only products created from
    # here onward default to True and get picked up by export_products_json.
    Product = apps.get_model('products', 'Product')
    Product.objects.all().update(is_dashboard_managed=False)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productimage_is_hero_productimage_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_dashboard_managed',
            field=models.BooleanField(default=True, help_text="Internal — leave this on. Only products created here (rather than bulk-imported from the existing site catalogue) are pushed to the live site by 'Export to website'."),
        ),
        migrations.RunPython(mark_existing_as_bulk_imported, migrations.RunPython.noop),
    ]
