# Generated by Django 6.1 on 2026-08-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_is_dashboard_managed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amazon_link',
            field=models.URLField(blank=True, help_text='Buy Now sends customers here.', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='Feature cards: [[icon, title, detail], ...]. Falls back to the category defaults when empty.'),
        ),
        migrations.AddField(
            model_name='product',
            name='gst_pct',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='As a fraction, e.g. 0.18 for 18%.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, help_text='Product video. Shown as the second thumbnail in the gallery.', null=True, upload_to='products/videos/'),
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='Use instead of uploading, when the video is already hosted (e.g. product-photos/<SKU>/video.mp4).', max_length=500),
        ),
    ]
