# Generated by Django 6.1 on 2026-08-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_amazon_link_product_features_product_gst_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='match_tier',
            field=models.CharField(blank=True, help_text='Internal provenance note carried over from the original site catalogue (how this row was matched during import). Nothing on the website reads it.', max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='specs',
            field=models.JSONField(blank=True, default=dict, help_text='Logistics/packaging details shown in the specification table (weight, pack dimensions, HSN code, manufacturer).'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_group',
            field=models.CharField(blank=True, db_index=True, help_text='Products sharing this value are shown as size options of one another on the website. Leave blank if this product has no size siblings.', max_length=64),
        ),
    ]
