# Generated by Django 6.1 on 2026-08-25 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_match_tier_product_specs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecification',
            name='variant',
            field=models.ForeignKey(blank=True, help_text="Leave blank for a spec that applies to the whole product. Set this to attach the spec to one specific size/variant only — e.g. so the '16 cm' variant lists its own diameter instead of the 14 cm one.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='amazon_link',
            field=models.URLField(blank=True, help_text='The Amazon listing for this exact size. Most sizes have their own. Leave blank to use the same link as the product above.', max_length=500),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='description',
            field=models.TextField(blank=True, help_text='The full description for this size. Leave blank to use the same description as the product above.'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='display_name',
            field=models.CharField(blank=True, help_text='The full product title for this size, exactly as it should appear on the website. Leave blank to use the same name as the product above.', max_length=200),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='features',
            field=models.JSONField(blank=True, default=None, help_text='Feature cards for this size: [[icon, title, detail], ...]. Leave blank to use the same features as the product above.', null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='highlight',
            field=models.CharField(blank=True, help_text='The one-line selling point shown under the title. Leave blank to use the same one as the product above.', max_length=300),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Untick to hide this size from the website without deleting it.'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='match_tier',
            field=models.CharField(blank=True, help_text='Internal provenance note carried over from the original site catalogue. Nothing on the website reads it.', max_length=64),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='MRP for this size, in rupees. Leave blank to use the same price as the product above.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, db_index=True, help_text="The complete item code for this size, exactly as it appears on the packaging (e.g. LI008). Leave blank to use the product's own SKU.", max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='tags',
            field=models.JSONField(blank=True, default=None, help_text='Search/filter tags for this size, as a list. Leave blank to use the same tags as the product above.', null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='video',
            field=models.FileField(blank=True, help_text='A video for this size only. Leave blank to use the same video as the product above.', null=True, upload_to='products/videos/'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='video_url',
            field=models.URLField(blank=True, help_text='Use instead of uploading, when the video for this size is already hosted somewhere. Leave blank to use the same one as the product above.', max_length=500),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Tick for the size that should be selected first when a customer opens this product.'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(help_text='The size or option label shown on the size selector, e.g. "22 cm", "1.5 L", \'15"\'. Must be unique within this product.', max_length=100),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Position in the size selector. Lower numbers appear first.'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku_suffix',
            field=models.CharField(blank=True, help_text='Old-style: added to the end of the product SKU to build this size\'s code. Only used when the full SKU below is blank. Leave blank and use "SKU" instead.', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='uniq_variant_name_per_product'),
        ),
    ]
