# Generated by Django 6.1 on 2026-08-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productspecification_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='image_url',
            field=models.URLField(blank=True, help_text='Only if this size has no photos of its own and its picture lives somewhere else on the web. Leave blank to use the photos below, or the picture on the product itself.', max_length=500),
        ),
    ]
