# Generated by Django 6.1 on 2026-08-25 12:50

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productvariant_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, validators=[products.models.validate_media_ref]),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_url',
            field=models.CharField(blank=True, help_text='Use instead of uploading, when the video is already hosted (e.g. product-photos/<SKU>/video.mp4).', max_length=500, validators=[products.models.validate_media_ref]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image_url',
            field=models.CharField(blank=True, help_text='Only if this size has no photos of its own and its picture lives somewhere else on the web. Leave blank to use the photos below, or the picture on the product itself.', max_length=500, validators=[products.models.validate_media_ref]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='video_url',
            field=models.CharField(blank=True, help_text='Use instead of uploading, when the video for this size is already hosted somewhere. Leave blank to use the same one as the product above.', max_length=500, validators=[products.models.validate_media_ref]),
        ),
    ]
