# Generated by Django 6.1 on 2026-09-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_duplicate_spec_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hero_overridden',
            field=models.BooleanField(default=False, help_text='Internal — set automatically when the main image is chosen here, so the nightly catalogue sync cannot put the old photo back.'),
        ),
    ]
