# Generated by Django 6.1 on 2026-09-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_hero_overridden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
    ]
