# Generated by Django 6.1 on 2026-09-11 05:51

from django.db import migrations, models


def carry_hero_flag_forward(apps, schema_editor):
    """hero_overridden becomes one entry in the general overridden_fields list.

    The two are the same idea — "the dashboard owns this, do not let the deploy
    sync overwrite it" — so the boolean is dropped in this migration and the
    products already carrying it have to keep their claim, or their chosen main
    image would be reverted by the very next deploy.
    """
    Product = apps.get_model('products', 'Product')
    for pk in Product.objects.filter(hero_overridden=True).values_list('pk', flat=True):
        Product.objects.filter(pk=pk).update(overridden_fields=['gallery', 'hero'])


def restore_hero_flag(apps, schema_editor):
    """Filtered in Python, not with __contains: the JSON containment lookup is
    unsupported on SQLite, so a rollback on a developer machine would crash."""
    Product = apps.get_model('products', 'Product')
    for pk, fields in Product.objects.values_list('pk', 'overridden_fields'):
        if 'hero' in (fields or ()):
            Product.objects.filter(pk=pk).update(hero_overridden=True)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_product_featured_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetiredSku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, help_text='What it was called, so the list is readable.', max_length=200)),
                ('retired_at', models.DateTimeField(auto_now_add=True)),
                ('retired_by', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Removed product',
                'verbose_name_plural': 'Removed products',
                'ordering': ['-retired_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, help_text='The grey summary under the Google result. Leave blank to use the highlight. Around 155 characters reads best.', max_length=320),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Browser tab and Google result heading. Leave blank to use the product name. Around 60 characters reads best.', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='overridden_fields',
            field=models.JSONField(blank=True, default=list, help_text="Internal — the parts of this product that were edited here and should no longer be taken from the website's catalogue file."),
        ),
        # Must sit between the two: the list column has to exist before the flag
        # can be copied into it, and the flag has to survive until it is copied.
        migrations.RunPython(carry_hero_flag_forward, restore_hero_flag),
        migrations.RemoveField(
            model_name='product',
            name='hero_overridden',
        ),
    ]
