# Generated by Django 6.1 on 2026-09-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_retiredsku_remove_product_hero_overridden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='overridden_fields',
            field=models.JSONField(blank=True, default=list, help_text='Internal — the parts of this that were edited here and should replace what the website ships.'),
        ),
        migrations.AddField(
            model_name='category',
            name='overridden_fields',
            field=models.JSONField(blank=True, default=list, help_text='Internal — the parts of this that were edited here and should replace what the website ships.'),
        ),
    ]
