# Generated by Django 6.1 on 2026-09-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0002_download_brand_download_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='category',
            field=models.CharField(choices=[('catalogue', 'Catalogue'), ('brochure', 'Brochure'), ('technical_sheet', 'Technical Sheet'), ('other', 'Other')], default='catalogue', help_text='"Catalogue" is the one wired to the Download PDF button on Catalogue.html.', max_length=20),
        ),
        migrations.AlterField(
            model_name='download',
            name='file',
            field=models.FileField(help_text='PDF file. The Catalogue page serves this directly, so upload the final artwork.', upload_to='downloads/'),
        ),
        migrations.AlterField(
            model_name='download',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Untick to retire this file without deleting it. The website skips inactive files.'),
        ),
        migrations.AlterField(
            model_name='download',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='download',
            name='title',
            field=models.CharField(help_text='Shown as the link tooltip on the website, e.g. "Crystal Catalogue 2026-27".', max_length=200),
        ),
    ]
