# Generated by Django 6.1 on 2026-10-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Shown under the picture, e.g. "HomeShop18 STAR Award". Leave blank for a plain certificate with no caption.', max_length=160)),
                ('subtitle', models.CharField(blank=True, help_text='The smaller second line, e.g. "Home & Kitchen".', max_length=160)),
                ('image', models.ImageField(blank=True, help_text='The certificate or trophy photograph. Landscape scans work best — they are shown about 168px tall and fitted whole, so nothing is cropped.', upload_to='awards/')),
                ('image_path', models.CharField(blank=True, help_text='Set automatically for the certificates the site already ships. Leave it alone and upload a picture above instead.', max_length=300)),
                ('pdf', models.FileField(blank=True, help_text='Optional. Attach the full certificate and the card becomes clickable — visitors open the PDF in a new tab.', null=True, upload_to='awards/pdf/')),
                ('alt', models.CharField(blank=True, help_text='What the picture shows, for screen readers and for when the image fails to load. Falls back to the title.', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lowest first. Ties fall back to the order they were added.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to take this off the site without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Award / certificate',
                'verbose_name_plural': 'Awards & certificates',
                'ordering': ['order', 'id'],
            },
        ),
    ]
