# Generated by Django 6.1 on 2026-10-06 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds_per_card', models.DecimalField(decimal_places=1, default=1, help_text='How long one certificate takes to go past. Lower is faster — 0.5 is brisk, 1 is the default, 3 gives people time to read a caption. Anything from 0.2 to 20.', max_digits=4, validators=[django.core.validators.MinValueValidator(0.2), django.core.validators.MaxValueValidator(20)], verbose_name='Seconds per certificate')),
                ('autoscroll', models.BooleanField(default=True, help_text='Untick to leave the strip still. Visitors can still drag or swipe through the certificates.', verbose_name='Scroll by itself')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scrolling speed',
                'verbose_name_plural': 'Scrolling speed',
            },
        ),
    ]
