# Generated by Django 6.1 on 2026-10-06 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_awardsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardsettings',
            name='seconds_per_card',
            field=models.DecimalField(decimal_places=1, default=0.6, help_text='How long one certificate takes to go past. Lower is faster. 0.6 is the default, 0.3 is quick, 3 gives people time to read a caption before it leaves. Anything from 0.2 to 20.', max_digits=4, validators=[django.core.validators.MinValueValidator(0.2), django.core.validators.MaxValueValidator(20)], verbose_name='Seconds per certificate'),
        ),
    ]
