# Generated by Django 6.1 on 2026-10-06 07:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_alter_awardsettings_seconds_per_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardsettings',
            name='seconds_per_card',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='<b>Leave this empty</b> and the certificates move at exactly the same pace as the product strip just above them on the page. Fill it in only to override that: it is how long one certificate takes to go past, so lower is faster — 0.3 is quick, 3 gives people time to read a caption. 0.2 to 20.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.2), django.core.validators.MaxValueValidator(20)], verbose_name='Seconds per certificate'),
        ),
    ]
