# Generated by Django 6.1 on 2026-09-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(db_index=True, help_text='The page this belongs to, exactly as the file is named, e.g. "About.html".', max_length=120)),
                ('section_key', models.SlugField(help_text='Matches the data-cms id on that element in the page HTML, e.g. "hero-heading".', max_length=120)),
                ('label', models.CharField(blank=True, help_text='What to call this in the list. Left blank, the section key is used.', max_length=160)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=10)),
                ('text_value', models.TextField(blank=True, help_text='Used when Kind is Text. Plain text -- shown exactly as typed, no HTML.')),
                ('image', models.ImageField(blank=True, help_text='Used when Kind is Image.', null=True, upload_to='page-sections/')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to fall back to the content the page already ships, without deleting this.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page section',
                'verbose_name_plural': 'Page sections',
                'ordering': ['page', 'section_key'],
                'unique_together': {('page', 'section_key')},
            },
        ),
    ]
