# Generated by Django 6.1 on 2026-09-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSectionTrash',
            fields=[
            ],
            options={
                'verbose_name': 'Page section (trash)',
                'verbose_name_plural': 'Page sections — Trash',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.pagesection',),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
