# Generated by Django 6.1 on 2026-09-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_pagesectiontrash_pagesection_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='section',
            field=models.CharField(blank=True, db_index=True, help_text='Which band of the page this sits in, e.g. "hero". Filled in automatically; it is only used to group this list.', max_length=120),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='shipped_value',
            field=models.TextField(blank=True, help_text='What the page shows today, for reference. Leave the value above empty and the page keeps showing this.'),
        ),
    ]
