# Generated by Django 6.1 on 2026-09-16 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_pagesection_section_pagesection_shipped_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='The file on the website, e.g. "About.html". This is what ties the page to its sections — do not change it.', max_length=120, unique=True)),
                ('title', models.CharField(help_text='What this page is called in the dashboard.', max_length=160)),
                ('group', models.CharField(blank=True, db_index=True, help_text='Heading this page is listed under, e.g. "Cookware".', max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['order', 'group', 'title'],
            },
        ),
        migrations.AddField(
            model_name='pagesection',
            name='image_mobile',
            field=models.ImageField(blank=True, help_text='Optional. A crop that suits a narrow screen — phones get this one instead. Leave empty and phones show the picture above.', null=True, upload_to='page-sections/mobile/', verbose_name='Phone picture'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='image',
            field=models.ImageField(blank=True, help_text='Used when Kind is Image. Shown on desktops and tablets, and on phones too unless a phone picture is set below.', null=True, upload_to='page-sections/'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='page_ref',
            field=models.ForeignKey(blank=True, help_text='Set automatically from the filename above.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.page', verbose_name='Page'),
        ),
    ]
