# Generated by Django 6.1 on 2026-09-16 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_backfill_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='page_ref',
            field=models.ForeignKey(blank=True, help_text='Set automatically from the filename above.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='content.page', verbose_name='Page'),
        ),
    ]
