# Generated by Django 6.1 on 2026-09-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_pagesection_page_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='expected_size',
            field=models.CharField(blank=True, help_text="For an image: the box it lands in on the page, worked out from that box's own CSS. Upload something close to this shape, or the site crops it to fit -- this is why a photo sometimes looks cut off after saving. Blank means the box has no fixed shape, so nothing is cropped.", max_length=200),
        ),
    ]
