# Generated by Django 6.1 on 2026-09-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_pagesection_expected_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='allow_html',
            field=models.BooleanField(default=False, help_text='Tick to write HTML here -- <br> for a line break, <b>bold</b>, <span style="color:#ED3338">colour</span>. Left unticked, tags are shown to visitors as the literal text you typed, which is almost never what you want.', verbose_name='Format with HTML'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='text_value',
            field=models.TextField(blank=True, help_text='Used when Kind is Text. Typed straight onto the page. Tick "Format with HTML" below to use tags and styling here.'),
        ),
    ]
