# Generated by Django 6.1 on 2026-09-29 09:32

from django.db import migrations, models


def carry_allow_html_over(apps, schema_editor):
    """Keep anything already ticked under the old boolean.

    0008 shipped a "Format with HTML" checkbox and was live before this change
    landed, so a section may already be relying on it. Dropping the column
    without reading it first would quietly put that section back to showing its
    tags as text -- the exact bug 0008 existed to fix.
    """
    PageSection = apps.get_model('content', 'PageSection')
    PageSection.objects.filter(allow_html=True).update(text_format='html')


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_pagesection_allow_html_alter_pagesection_text_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='text_format',
            field=models.CharField(choices=[('plain', 'Plain text'), ('list', 'Heading + bullet list'), ('html', 'HTML')], default='plain', help_text='Plain text is typed onto the page exactly as written. "Heading + bullet list" turns the first line into a bold lead and every line after it starting with "-" into a red bullet, the way the category heroes look. HTML lets you write tags and inline styles yourself.', max_length=10, verbose_name='Show this as'),
        ),
        migrations.RunPython(carry_allow_html_over,
                             migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='pagesection',
            name='allow_html',
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='text_value',
            field=models.TextField(blank=True, help_text='Used when Kind is Text. How it is rendered is set by "Show this as" below.'),
        ),
    ]
